import type {
  Artifact,
  Resource,
  StructuredDocumentBlock,
} from "../../types/content";
import { ASSET_IDS } from "./assets";
import { bellabeatSupportingResources } from "./bellabeat-resources";

export const ARTIFACT_IDS = {
  bellabeat: "artifact-bellabeat-wellness-analysis",
  resume: "artifact-resume",
  contact: "artifact-contact",
  about: "artifact-about",
  reservoirStudy: "artifact-reservoir-interface-study",
  brandSymbol: "artifact-kodyepugh-symbol",
} as const;

export const RESOURCE_IDS = {
  bellabeatRepository: "resource-bellabeat-wellness-analysis-repository",
} as const;

export const RESUME_DOCUMENT_BLOCKS = [
  {
    id: "professional-summary",
    type: "paragraph",
    text: "Analyst and digital product professional with experience redesigning a federal task-tracking workflow, building CMS structures and information architectures for three client organizations, and analyzing more than 15 million rows of wellness data in BigQuery. Uses SQL, Excel, Tableau, Python, requirements analysis, and stakeholder communication to clarify operational problems, improve processes, and support data-informed decisions.",
  },
  { id: "skills", type: "heading", level: 2, text: "Skills" },
  {
    id: "skills-data-analytics",
    type: "paragraph",
    text: "**Data & Analytics:** SQL, BigQuery, Excel, Tableau; data cleaning, data validation, exploratory analysis, aggregation, visualization, reporting",
  },
  {
    id: "skills-product-operations",
    type: "paragraph",
    text: "**Product & Operations:** business analysis, requirements analysis, process improvement, workflow design, information architecture, project coordination, stakeholder communication, presentation",
  },
  {
    id: "skills-programming-web",
    type: "paragraph",
    text: "**Programming & Web:** Python, Git/GitHub, HTML/CSS, JavaScript, Velo, Wix Studio, Wix CMS, WordPress",
  },
  {
    id: "selected-data-analytics-project",
    type: "heading",
    level: 2,
    text: "Selected Data Analytics Project",
  },
  {
    id: "bellabeat-wellness-behavior-analysis",
    type: "entry",
    title: "Bellabeat Wellness-Behavior Analysis",
    meta: "2026",
    subtitle: "Independent Data Analytics Case Study",
    items: [
      "Built a reproducible workflow for 29 Fitbit source tables and more than 15 million rows. Used Excel for source inspection, BigQuery/Standard SQL for profiling, transformation, joins, aggregation, and validation, Python for exploratory analysis, and Git for version control.",
      "Preserved raw source data and separated the workflow into staging, cleaned, analytical, and reporting layers; investigated duplicate boundaries, uneven feature coverage, unresolved user identity, and differences among daily, hourly, minute, and second-level records before defining defensible analytical units.",
      "Analyzed 1,935 observed activity session-days and found that light activity accounted for 84.9% of active minutes; used the finding to frame testable Bellabeat app hypotheses around personal baselines, approachable movement, and user-controlled timing.",
      "Used sensitivity testing to rule out unsupported segmentation and causal claims; documented the study's limits and the additional data needed for future product experiments, and kept the analysis traceable from source data through QA and publication.",
    ],
  },
  {
    id: "professional-experience",
    type: "heading",
    level: 2,
    text: "Professional Experience",
  },
  {
    id: "independent-consultant",
    type: "entry",
    title: "Independent Web & Digital Product Consultant",
    meta: "2025 - Present",
    subtitle: "Client Website Reconstruction & Product Support",
    items: [
      "Reconstructed three client websites from stakeholder requirements, designing clear information architectures, CMS structures, content workflows, responsive interfaces, and maintainable production sites.",
    ],
  },
  { id: "cif-oakland", type: "heading", level: 4, text: "CIF Oakland City Section" },
  {
    id: "cif-oakland-details",
    type: "list",
    style: "unordered",
    items: [
      "Configured structured relationships in Wix CMS among sports, schools, tournaments, participating teams, tournament rounds, and games to support schedules, results, standings, championships, and public communications.",
      "Design and maintain workflows for schedules, results, standings, and playoff brackets within Wix's platform constraints as organizational, content, and functionality needs evolve.",
    ],
  },
  { id: "workforce-development", type: "heading", level: 4, text: "Workforce Development Unit" },
  {
    id: "workforce-development-details",
    type: "list",
    style: "unordered",
    items: [
      "Turned an incomplete Wix implementation with placeholder content, unclear navigation, inconsistent branding, missing service information, and usability gaps into a production-ready site organized around education pathways, workforce development, leadership, partnerships, and consulting services.",
    ],
  },
  { id: "gospelfest-oakland", type: "heading", level: 4, text: "GospelFest Oakland" },
  {
    id: "gospelfest-oakland-details",
    type: "list",
    style: "unordered",
    items: [
      "Reconstructed the site as an event platform for ticketing, fundraising, sponsorship, artist outreach, and visitor information. During the event cycle, the organization met its fundraising goal and sold all available tickets; the site also generated inquiries from 28 local artists.",
    ],
  },
  {
    id: "federal-student-aid",
    type: "entry",
    title: "U.S. Department of Education - Federal Student Aid",
    meta: "Jan 2025 - Feb 2025",
    subtitle: "Management & Program Analyst, Digital Delivery Division | Washington, DC",
    items: [
      "Identified a process-control weakness in an Excel task tracker that required employees to interpret assigned dates and manually update color-coded status indicators.",
      "Redesigned the tracker with date-based conditional formatting to automatically flag approaching and missed deadlines; secured supervisor approval and led a team walkthrough of the revised workflow.",
    ],
  },
  {
    id: "netflix-productions",
    type: "entry",
    title: "Netflix Productions",
    meta: "Oct 2023 - Mar 2024",
    subtitle: "Director's Assistant | Los Angeles, CA",
    supporting: "*Monster(s): The Lyle and Erik Menendez Story - Episodes 201 & 202*",
    items: [
      "Served as liaison between director Carl Franklin and production departments on a multimillion-dollar television production, coordinating time-sensitive communication across teams.",
      "Coordinated housing, technology, equipment, and other off-set operational requirements alongside changing production schedules.",
      "Managed and reported recurring expenditures for the director's off-set operations, maintained accurate records, and supported day-to-day decisions.",
    ],
  },
  {
    id: "additional-experience",
    type: "heading",
    level: 2,
    text: "Additional Experience",
  },
  {
    id: "various-production-companies",
    type: "entry",
    title: "Various Production Companies",
    meta: "2021 - 2023",
    subtitle: "Freelance Set Production Assistant | Los Angeles, CA",
    items: [
      "Coordinated real-time communication between production leadership and on-set teams, relayed changing requirements, managed production areas, and responded to time-sensitive logistics.",
      "Selected credits: Oppenheimer, Poolman, Monster: The Jeffrey Dahmer Story, and other feature and television productions.",
    ],
  },
  {
    id: "student-athlete",
    type: "entry",
    title: "Stanford University & Loyola Marymount University",
    meta: "2016 - 2021",
    subtitle: "NCAA Division I Men's Basketball Student-Athlete",
    items: [
      "Five-year NCAA Division I student-athlete; three-time Pac-12 All-Academic selection and NABC Honors Court honoree.",
    ],
  },
  { id: "education", type: "heading", level: 2, text: "Education" },
  {
    id: "loyola-marymount-university",
    type: "entry",
    title: "Loyola Marymount University",
    meta: "2024",
    subtitle: "Master of Fine Arts, Film & Television Production (Directing Fiction)",
  },
  {
    id: "stanford-university",
    type: "entry",
    title: "Stanford University",
    meta: "2020",
    subtitle: "Bachelor of Arts, Film & Media Studies (Film, Media and Technology)",
    supporting: "Relevant technical coursework: Programming Methodology, Programming Abstractions, Calculus I-III, Introductory Electronics I-II",
  },
  { id: "certifications", type: "heading", level: 2, text: "Certifications" },
  {
    id: "google-data-analytics-certificate",
    type: "entry",
    title: "Google Data Analytics Professional Certificate",
    meta: "Aug 2026",
    subtitle: "Google / Coursera",
  },
  {
    id: "finance-quantitative-modeling-certificate",
    type: "entry",
    title: "Finance & Quantitative Modeling for Analysts Specialization",
    meta: "Jul 2024",
    subtitle: "Wharton Online / Coursera",
  },
  {
    id: "resume-pdf-download",
    type: "download",
    assetId: ASSET_IDS.resumePdf,
    label: "Download PDF",
  },
] satisfies readonly StructuredDocumentBlock[];

export const BELLABEAT_DOCUMENT_BLOCKS = [
  {
    id: "interpretation-boundary",
    type: "callout",
    title: "Interpretation boundary",
    tone: "important",
    text: "The case describes 30 consenting Fitbit users, but the files contain 35 export/session identifiers and no authoritative session-to-user mapping. This article uses session profiles, not verified people. The results are historical, non-causal, and not representative of Bellabeat customers.",
  },
  {
    id: "project-overview",
    type: "heading",
    level: 2,
    text: "Project Overview",
  },
  {
    id: "project-overview-body",
    type: "paragraph",
    text: "This project turns a public, historical Fitbit export into a controlled wellness-behavior analysis and three testable product directions for the Bellabeat app. I used Excel for initial inspection, then selected BigQuery and Standard SQL when minute- and second-level files exceeded a spreadsheet's comfortable capacity. I preserved the source files, separated protected raw data from cleaned and analytical layers, documented material decisions, validated each transformation, and translated the evidence into a concise product narrative.",
  },
  {
    id: "business-objective",
    type: "heading",
    level: 2,
    text: "Business Objective",
  },
  {
    id: "business-objective-body",
    type: "paragraph",
    text: "Bellabeat's case question is how smart-device usage trends could inform marketing strategy. I focused on the Bellabeat app because it is the shared layer where recorded behavior can become understandable feedback, customer-controlled prompts, feature education, and adaptive routines.",
  },
  {
    id: "business-objective-boundary",
    type: "paragraph",
    text: "The decision was not what describes an average wearable user. The export does not support that claim. The decision was which observed patterns are reliable enough to prioritize low-risk Bellabeat app experiments, and what evidence Bellabeat would need before scaling them. These recommendations are hypotheses for testing with current, consented customers; they do not estimate campaign return, clinical benefit, retention, or causal product impact.",
  },
  {
    id: "business-objective-audience",
    type: "paragraph",
    text: "Bellabeat serves a women-focused audience, but the source contains no reliable sex, gender, age, or broader demographic fields. I therefore did not infer women-specific behavior or claim audience representativeness.",
  },
  {
    id: "from-source-files-to-bigquery",
    type: "heading",
    level: 2,
    text: "From Source Files to BigQuery",
  },
  {
    id: "source-files-body",
    type: "paragraph",
    text: "The data originated as public Fitbit CSV files distributed through Kaggle and attributed there to Zenodo. They cover March 12-April 11 and April 12-May 12, 2016, for up to 62 calendar dates. Excel inspection established filenames, schemas, date formats, feature families, and obvious quality issues.",
  },
  {
    id: "bigquery-body",
    type: "paragraph",
    text: "The validated activity-minute table contains 2,760,120 clean rows, and staged heart rate contains 3,638,339 rows. BigQuery was the scalable analytical environment—not the origin of the data. I used Standard SQL and the BigQuery CLI to move from protected source tables through staging, clean, hourly/daily, analytical, and reporting layers.",
  },
  {
    id: "analytical-approach",
    type: "heading",
    level: 2,
    text: "Analytical Approach",
  },
  {
    id: "analytical-approach-grain",
    type: "paragraph",
    text: "The most consequential choice was to treat the first-column identifier as an export/session key. The case says 30 consenters while the files contain 35 identifiers, so every count and relationship is labeled at the session, session-day, session-hour, feature-log, or timestamp grain.",
  },
  {
    id: "analytical-approach-quality",
    type: "paragraph",
    text: "Recorded zero-step days were preserved and missing dates remained missing. A complete activity day was defined as exactly 1,440 minute rows, then used as a sensitivity rather than a filter on the main story. Daily activity and sleep keys were validated before joining; sleep was assigned to its end date; and selected sedentary time subtracts timestamp-overlapping recorded sleep.",
  },
  {
    id: "analytical-approach-validation",
    type: "paragraph",
    text: "Relationships were separated into within-session and between-session questions. A fixed clustering taxonomy was retired after feature reduction produced unstable assignments. QA covered row counts, key uniqueness, nulls, valid ranges, and reconciliation; the final analytical pipeline passed all 25 required validation checks.",
  },
  {
    id: "three-core-findings",
    type: "heading",
    level: 2,
    text: "Three Core Findings",
  },
  {
    id: "finding-movement",
    type: "heading",
    level: 3,
    text: "1. Movement varies, making personal baselines more defensible than universal targets",
  },
  {
    id: "finding-movement-body",
    type: "paragraph",
    text: "Across 1,935 observed session-days, steps averaged 7,200 and had a median of 6,835. Alternative estimates remained directionally similar: 6,857 with equal session weighting, 7,196 with equal date weighting, and 7,280 on complete days. The spread is substantial, so these values describe the export; they are not a recommended target.",
  },
  {
    id: "figure-daily-steps-distribution",
    type: "figure",
    resourceId: "resource-bellabeat-daily-steps-distribution",
    representationId: "representation-bellabeat-daily-steps-distribution",
    alt: "Histogram of 1,935 observed session-days showing a right-skewed daily-step distribution, with labeled pooled mean 7,200, median 6,835, and equal-session mean 6,857.",
  },
  {
    id: "finding-light-activity",
    type: "heading",
    level: 3,
    text: "2. Light activity is the broadest accessible opportunity",
  },
  {
    id: "finding-light-activity-body",
    type: "paragraph",
    text: "Light activity contributed 84.9% of recorded active minutes. Within sessions, steps were strongly associated with active minutes (r=0.824) and moderately inversely associated with selected sedentary minutes (r=-0.427). These associations support testing approachable movement content, not promising a causal or medical result.",
  },
  {
    id: "figure-activity-intensity",
    type: "figure",
    resourceId: "resource-bellabeat-activity-intensity-composition",
    representationId: "representation-bellabeat-activity-intensity-composition",
    alt: "Horizontal bars showing mean recorded light, fairly active, and very active minutes per observed session-day, with light activity at 185.5 minutes and 84.9% of active minutes.",
  },
  {
    id: "finding-routines",
    type: "heading",
    level: 3,
    text: "3. Routines differ, and fixed customer types do not survive validation",
  },
  {
    id: "finding-routines-body",
    type: "paragraph",
    text: "Adequately observed session profiles peaked at different hours from 06:00 to 20:00. Weekend activity split evenly: 17 eligible sessions were higher and 17 were lower than their weekday average. The session-by-date heatmap shows standardized daily trajectories and missing dates; it does not visualize hourly timing.",
  },
  {
    id: "figure-session-heatmap",
    type: "figure",
    resourceId: "resource-bellabeat-session-activity-heatmap",
    representationId: "representation-bellabeat-session-activity-heatmap",
    alt: "Heatmap with neutral session labels S01-S35 across March-May dates, showing within-session standardized daily steps and gray missing dates distinct from observed low or zero-step days.",
  },
  {
    id: "finding-segmentation-body",
    type: "paragraph",
    text: "The original clusters changed sharply after correlated features were reduced (ARI=0.084), and leave-one-session stability fell to 0.034. Continuous baselines and preferences are safer than fixed identities.",
  },
  {
    id: "figure-segmentation-stability",
    type: "figure",
    resourceId: "resource-bellabeat-segmentation-stability",
    representationId: "representation-bellabeat-segmentation-stability",
    alt: "Horizontal bars showing original, reduced-feature, and MET-added silhouette values plus adjusted Rand index stability values, including original-versus-reduced ARI 0.084 and minimum leave-one-session ARI 0.034.",
  },
  {
    id: "finding-feature-coverage-body",
    type: "paragraph",
    text: "Feature coverage explains why personalization also needs consent and readiness checks: activity/METs appear for 35 session identifiers, sleep for 25, heart rate for 15, and weight for 13. Presence is not engagement, and absence is not churn.",
  },
  {
    id: "figure-recording-feature-presence",
    type: "figure",
    resourceId: "resource-bellabeat-recording-feature-presence",
    representationId: "representation-bellabeat-recording-feature-presence",
    alt: "Three-panel chart showing activity recording completeness, feature data present for activity, sleep, heart rate, and weight session identifiers, and the increasingly selective weight-record cadence thresholds.",
  },
  {
    id: "recommendations",
    type: "heading",
    level: 2,
    text: "Recommendations",
  },
  {
    id: "recommendation-progress",
    type: "heading",
    level: 3,
    text: "1. Progress is personal",
  },
  {
    id: "recommendation-progress-body",
    type: "paragraph",
    text: "Test rolling personal-baseline feedback with customer-adjustable next steps. Measure qualified return, baseline-card engagement, and change from the customer's pre-period; guard against unsafe escalation, opt-out, and adverse sentiment.",
  },
  {
    id: "recommendation-movement",
    type: "heading",
    level: 3,
    text: "2. Small movement counts",
  },
  {
    id: "recommendation-movement-body",
    type: "paragraph",
    text: "Test short, accessible movement options such as a walk, stretch, or movement break. Measure content completion, incremental active minutes, and retained engagement; monitor fatigue, dismissals, and accessibility feedback.",
  },
  {
    id: "recommendation-timing",
    type: "heading",
    level: 3,
    text: "3. Your routine, your timing",
  },
  {
    id: "recommendation-timing-body",
    type: "paragraph",
    text: "Test customer-selected timing against fixed and consented adaptive timing. Allow weekday and weekend preferences to differ. Measure action after delivery and weekly engagement; protect quiet hours, frequency limits, and opt-out control.",
  },
  {
    id: "recommendation-sleep-body",
    type: "paragraph",
    text: "Sleep feedback should remain optional and descriptive because coverage is selective and prior activity has essentially no within-session relationship with same-night recorded sleep (r=0.024). Before any recovery or re-engagement automation, Bellabeat needs telemetry that distinguishes app use, sync status, device state, delivery, feature enrollment, and customer preference.",
  },
  {
    id: "limitations-and-next-steps",
    type: "heading",
    level: 2,
    text: "Limitations and Next Steps",
  },
  {
    id: "limitations-body",
    type: "paragraph",
    text: "The source is historical, observational, demographically incomplete, and uneven across features. It has no verified person mapping, wear-state confirmation, Bellabeat product exposure, campaign outcomes, revenue, or retention labels. Distance and body fat are excluded; weight is cadence-only; heart rate is non-medical and appendix-only. Correlations and paired differences do not establish intervention effects.",
  },
  {
    id: "next-steps-body",
    type: "paragraph",
    text: "The next phase should validate current identifiers and consent rules, instrument first-party events, establish personal baselines, reconcile telemetry in a small QA cohort, and run customer-level experiments with preregistered outcomes and guardrails. Bellabeat should scale only if benefits persist beyond novelty and do not increase fatigue, opt-outs, adverse sentiment, or accessibility concerns.",
  },
  {
    id: "comprehensive-case-study",
    type: "heading",
    level: 2,
    text: "Comprehensive Case Study",
  },
  {
    id: "comprehensive-case-study-body",
    type: "paragraph",
    text: "The comprehensive report contains the five-theme narrative, all ten approved figures, complete decision register, metric definitions, lineage, QA evidence, recommendation measurement plan, and source traceability.",
  },
  {
    id: "comprehensive-case-study-link",
    type: "link",
    label: "Open the comprehensive case study",
    resourceId: "resource-bellabeat-comprehensive-case-study",
  },
] satisfies readonly StructuredDocumentBlock[];

export const resources = [
  {
    objectType: "resource",
    id: ARTIFACT_IDS.bellabeat,
    slug: "bellabeat-wellness-analysis",
    title: "Bellabeat Wellness-Behavior Analysis",
    subtitle: "From Public Fitbit Files to Testable App Strategy",
    description:
      "Excel initial inspection; BigQuery + Standard SQL; controlled session-level interpretation across 1,935 observed session-days, with 84.9% light-activity share. Test personal progress, approachable movement, and customer-controlled timing. Historical and non-causal.",
    type: "case-study",
    inspectionKind: "structured-document",
    isArtifact: true,
    category: "Data / Analytics",
    categoryColor: "#28758c",
    date: "August 2026",
    medium: "document",
    relationships: [{ relation: "by", label: "Kodye Pugh" }, { relation: "for", label: "Bellabeat" }],
    createdAt: "2026-08-21",
    updatedAt: "2026-08-22",
    format: "Case study",
    featured: true,
    published: true,
    representations: [
      {
        id: "representation-bellabeat-recruiter-summary-markdown",
        kind: "external",
        url: "https://github.com/kodyepugh/bellabeat-wellness-analysis/blob/main/reports/portfolio/bellabeat_recruiter_summary.md",
        label: "Recruiter summary (Markdown)",
        sourceLabel: "Bellabeat analysis repository",
      },
      {
        id: "representation-bellabeat-recruiter-summary-html",
        kind: "external",
        url: "https://github.com/kodyepugh/bellabeat-wellness-analysis/blob/main/reports/portfolio/bellabeat_recruiter_summary.html",
        label: "Recruiter summary (HTML)",
        sourceLabel: "Bellabeat analysis repository",
      },
    ],
    content: {
      kind: "structured-document",
      status: "ready",
      blocks: BELLABEAT_DOCUMENT_BLOCKS,
    },
  },
  {
    objectType: "resource",
    id: RESOURCE_IDS.bellabeatRepository,
    slug: "bellabeat-wellness-analysis-repository",
    title: "Bellabeat Wellness Analysis Repository",
    subtitle: "Canonical source code and analysis files",
    description: "The public GitHub repository containing the Bellabeat portfolio analysis.",
    type: "repository",
    inspectionKind: "external-link",
    isArtifact: false,
    category: "Data / Analytics",
    categoryColor: "#28758c",
    medium: "link",
    relationships: [{ relation: "by", label: "Kodye Pugh" }],
    createdAt: "2026-08-21",
    updatedAt: "2026-08-22",
    format: "Repository",
    published: true,
    representations: [
      {
        id: "representation-bellabeat-wellness-analysis-repository-github",
        kind: "external",
        url: "https://github.com/kodyepugh/bellabeat-wellness-analysis",
        label: "GitHub repository",
        sourceLabel: "GitHub",
        order: 1,
        published: true,
      },
    ],
    content: {
      kind: "external-link",
      status: "ready",
      url: "https://github.com/kodyepugh/bellabeat-wellness-analysis",
      label: "Open GitHub repository",
    },
  },
  {
    objectType: "resource",
    id: ARTIFACT_IDS.resume,
    slug: "resume",
    title: "Resume",
    subtitle: "Experience, capabilities, and selected engagements",
    type: "resume",
    inspectionKind: "structured-document",
    isArtifact: true,
    category: "Practice / Experience",
    categoryColor: "#667d83",
    medium: "document",
    relationships: [{ relation: "on", label: "Kodye Pugh" }],
    createdAt: "2026-08-22",
    updatedAt: "2026-08-22",
    format: "Resume",
    footerNavigation: true,
    footerNavigationOrder: 1,
    featured: true,
    published: true,
    representations: [
      {
        id: "representation-resume-pdf",
        kind: "asset",
        assetId: ASSET_IDS.resumePdf,
        label: "Approved resume PDF",
        order: 1,
        published: true,
      },
    ],
    content: {
      kind: "structured-document",
      status: "ready",
      presentationProfile: "compact",
      blocks: RESUME_DOCUMENT_BLOCKS,
    },
  },
  {
    objectType: "resource",
    id: ARTIFACT_IDS.contact,
    slug: "contact",
    title: "Contact",
    subtitle: "Email, LinkedIn, and GitHub",
    description: "Approved professional contact destinations.",
    type: "profile",
    inspectionKind: "contact-form",
    isArtifact: true,
    category: "Connection",
    categoryColor: "#6f8065",
    medium: "form",
    relationships: [{ relation: "for", label: "Kodye Pugh" }],
    createdAt: "2026-08-22",
    updatedAt: "2026-08-22",
    format: "Links",
    footerNavigation: true,
    footerNavigationOrder: 2,
    featured: true,
    published: true,
    content: {
      kind: "contact",
      status: "ready",
      socialLinks: [
        {
          provider: "linkedin",
          url: "https://www.linkedin.com/in/kodyepugh/",
        },
        {
          provider: "github",
          url: "https://github.com/kodyepugh",
        },
      ],
    },
  },
  {
    objectType: "resource",
    id: ARTIFACT_IDS.about,
    slug: "about",
    title: "About",
    subtitle: "A working portrait of practice, context, and intent",
    type: "profile",
    inspectionKind: "structured-document",
    isArtifact: true,
    category: "About / Self",
    categoryColor: "#8d7257",
    medium: "other",
    footerNavigation: true,
    footerNavigationOrder: 3,
    createdAt: "2026-08-19",
    updatedAt: "2026-08-22",
    featured: true,
    published: false,
    content: {
      kind: "rich-text",
      status: "placeholder",
      body: [
        "A working portrait of practice, context, and intent.",
        "TODO: Add approved biography copy.",
      ],
    },
  },
  {
    objectType: "resource",
    id: ARTIFACT_IDS.reservoirStudy,
    slug: "reservoir-interface-study",
    title: "Reservoir Interface Study",
    subtitle: "A spatial navigation prototype",
    type: "project",
    inspectionKind: "structured-document",
    isArtifact: true,
    category: "Web / Interaction",
    categoryColor: "#b9573f",
    date: "2026",
    medium: "other",
    createdAt: "2026-08-17",
    updatedAt: "2026-08-22",
    format: "Interactive website",
    featured: true,
    published: false,
    content: {
      kind: "case-study",
      status: "placeholder",
      sections: [
        {
          id: "overview",
          heading: "Overview",
          body: [
            "The Digital Reservoir is a spatial interface layered over semantic, conventional web content.",
            "TODO: Add approved project narrative, process evidence, and implementation details.",
          ],
        },
      ],
    },
  },
  {
    objectType: "resource",
    id: ARTIFACT_IDS.brandSymbol,
    slug: "kodyepugh-symbol",
    title: "Kodye Pugh Symbol",
    type: "image",
    inspectionKind: "image",
    isArtifact: true,
    category: "Identity",
    categoryColor: "#6f8065",
    medium: "image",
    relationships: [{ relation: "by", label: "Kodye Pugh" }],
    createdAt: "2026-08-17",
    updatedAt: "2026-08-22",
    format: "SVG",
    published: true,
    representations: [
      {
        id: "representation-kodyepugh-symbol-svg",
        kind: "asset",
        assetId: ASSET_IDS.brandSymbol,
        label: "Public SVG",
        order: 1,
        published: true,
      },
    ],
    content: {
      kind: "media",
      status: "ready",
      assetId: ASSET_IDS.brandSymbol,
    },
  },
  ...bellabeatSupportingResources,
] satisfies readonly Resource[];

export const artifacts = resources.filter(
  (resource) => resource.isArtifact === true,
) as readonly Artifact[];
